FROM maven:3.9.8-eclipse-temurin-17-alpine AS build
WORKDIR /workspace
COPY . .
ARG MODULE_NAME
RUN mvn -f pom.xml -pl "${MODULE_NAME}" -am -DskipTests package

FROM eclipse-temurin:17-jre-alpine
RUN apk add --no-cache curl
WORKDIR /app
ARG MODULE_NAME
COPY --from=build /workspace/${MODULE_NAME}/target/*.jar /app/app.jar
ENTRYPOINT ["java","-jar","/app/app.jar"]
